default:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  image: docker:19.03.9
  services:
    - docker:19.03.9-dind
  tags:
    - docker
    - linux

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  variables:
    IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
    IMAGE_TAG_REF: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    IMAGE_TAG_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG_REF || true
    - docker pull $IMAGE_TAG_LATEST || true
  script:
    - DOCKER_BUILDKIT=1 docker build
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $IMAGE_TAG_REF
      --cache-from $IMAGE_TAG_LATEST
      --tag $IMAGE_TAG_LATEST
      --tag $IMAGE_TAG_REF
      --tag $IMAGE_TAG_SHA
      .
    - docker push $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_SHA
